// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-books.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-books.ts
var search_books_default = defineTool({
  name: "search_books",
  title: "Search books",
  description: "Search the reading library for books by title, author, or tag. Returns metadata (title, author, category, status, read date), not the full note body.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text matched against title and author."),
    status: z.enum(["\uC791\uC131\uC911", "\uC644\uB8CC", "\uB300\uAE30"]).optional().describe("Filter by writing status."),
    category: z.string().trim().optional().describe("Filter by category name."),
    limit: z.number().int().optional().describe("Max rows to return (default 20, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, status, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("books").select("id,title,author,category,status,tags,read_date,updated_at,is_hidden").order("updated_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (status) q = q.eq("status", status);
    if (category) q = q.eq("category", category);
    if (query) {
      const term = query.normalize("NFC").replace(/[%,]/g, " ").trim();
      if (term) q = q.or(`title.ilike.%${term}%,author.ilike.%${term}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { books: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-book.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_book_default = defineTool2({
  name: "get_book",
  title: "Get book note",
  description: "Fetch one book from the reading library including its full markdown reading note. Look up by id, or by exact title.",
  inputSchema: {
    id: z2.string().trim().optional().describe("Book id (uuid)."),
    title: z2.string().trim().optional().describe("Exact book title, used when no id is given.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, title }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!id && !title) {
      return { content: [{ type: "text", text: "Provide either id or title." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("books").select("*").limit(1);
    q = id ? q.eq("id", id) : q.eq("title", title.normalize("NFC"));
    const { data, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Book not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { book: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List the reading library's categories in their configured display order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("categories").select("id,name,sort_order").order("sort_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-book.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var update_book_default = defineTool4({
  name: "update_book_metadata",
  title: "Update book metadata",
  description: "Update metadata for one book in the reading library: status, category, read date, tags, or visibility. Only the library owner can do this.",
  inputSchema: {
    id: z3.string().trim().describe("Book id (uuid)."),
    status: z3.enum(["\uC791\uC131\uC911", "\uC644\uB8CC", "\uB300\uAE30"]).optional().describe("New writing status."),
    category: z3.string().trim().optional().describe("New category name."),
    read_date: z3.string().trim().optional().describe("Read date as YYYY-MM-DD."),
    tags: z3.array(z3.string()).optional().describe("Replacement tag list."),
    is_hidden: z3.boolean().optional().describe("Hide the book from the public library.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status, category, read_date, tags, is_hidden }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const fields = {};
    if (status !== void 0) fields.status = status;
    if (category !== void 0) fields.category = category.normalize("NFC");
    if (read_date !== void 0) fields.read_date = read_date;
    if (tags !== void 0) fields.tags = tags.map((t) => t.normalize("NFC"));
    if (is_hidden !== void 0) fields.is_hidden = is_hidden;
    if (Object.keys(fields).length === 0) {
      return { content: [{ type: "text", text: "No fields to update." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("books").update(fields).eq("id", id).select("id,title,author,category,status,tags,read_date,is_hidden");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "No book updated \u2014 check the id and your permissions." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0]) }],
      structuredContent: { book: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bdlcjyrhbtbobdkahvus";
var mcp_default = defineMcp({
  name: "bookreview-sync",
  title: "BookReview Sync",
  version: "0.1.0",
  instructions: "Tools for the UGEN \uCC45\uC7A5 reading library. Use `search_books` to find books by title, author, status, or category; `get_book` to read a book's full markdown reading note; `list_categories` for the category list; and `update_book_metadata` to change a book's status, category, read date, tags, or visibility.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_books_default, get_book_default, list_categories_default, update_book_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
